### ISSUE TITLE
Simulate returns incorrect time step/range

### ISSUE THREAD

**Issue by kirichoi** [sys-bio/roadrunner#218]
Moved from Matthias' email:

The created timepoints are wrong:
```
result = rr.simulate(start=0, end=10, steps=5)
# wrong number of points ! this should be 6 points, and stop at 10
# but is 51 points and stops at 5 !!!! (SOMETHING IS REALLY WRONG HERE)
```
Example SBML with python code attached. I used the 1.3.32a release build from source.

Can be reproduced in v1.4.0 by:
```
import roadrunner
print roadrunner.__version__
# 1.4.0; Compiler: gcc 4.8.4, C++ version: 199711; JIT Compiler: LLVM-3.4; Date: Oct 14 2015, 00:00:59

# Load model results in warnings about fbc v2
rr = roadrunner.RoadRunner("toy_ode_update.xml")

# create a selection array
sel = ['time'] \
        + ["".join(["[", item, "]"]) for item in rr.model.getBoundarySpeciesIds()] \
        + ["".join(["[", item, "]"]) for item in rr.model.getFloatingSpeciesIds()]
print sel

# set the selection !!! NOT WORKING ANY MORE. Why is it not possible ????
rr.timeCourseSelections = sel
result = rr.simulate(start=0, end=10, steps=5)
print result
```
Model:
```
<?xml version="1.0" encoding="UTF-8"?>
<sbml xmlns="http://www.sbml.org/sbml/level3/version1/core" xmlns:fbc="http://www.sbml.org/sbml/level3/version1/fbc/version2" level="3" version="1" fbc:required="false">
  <model id="ode_update_toy" name="ODE metabolite update submodel" fbc:strict="false">
    <listOfCompartments>
      <compartment id="ext" name="external compartment" spatialDimensions="3" size="1" constant="true"/>
      <compartment id="cell" name="cell" spatialDimensions="3" size="1" constant="true"/>
    </listOfCompartments>
    <listOfSpecies>
      <species id="A" name="A" compartment="ext" initialAmount="10" hasOnlySubstanceUnits="false" boundaryCondition="true" constant="false"/>
      <species id="C" name="C" compartment="ext" initialAmount="0" hasOnlySubstanceUnits="false" boundaryCondition="true" constant="false"/>
      <species id="B1" name="B1" compartment="cell" initialAmount="0" hasOnlySubstanceUnits="false" boundaryCondition="false" constant="false"/>
      <species id="B2" name="B2" compartment="cell" initialAmount="0" hasOnlySubstanceUnits="false" boundaryCondition="false" constant="false"/>
    </listOfSpecies>
    <listOfParameters>
      <parameter id="ub_R1" name="ub R1" value="1" constant="false"/>
      <parameter id="lb" name="lower bound" value="0" constant="true"/>
      <parameter id="ub" name="upper bound" value="1000" constant="true"/>
      <parameter id="v_R1" name="R1 flux" value="0" constant="false"/>
      <parameter id="v_R2" name="R2 flux" value="0" constant="false"/>
      <parameter id="v_R3" name="R3 flux" value="0" constant="false"/>
    </listOfParameters>
    <listOfReactions>
      <reaction id="R1" name="A import (R1)" reversible="true" fast="false" fbc:lowerFluxBound="lb" fbc:upperFluxBound="ub_R1">
        <listOfReactants>
          <speciesReference species="A" stoichiometry="1" constant="true"/>
        </listOfReactants>
        <listOfProducts>
          <speciesReference species="B1" stoichiometry="1" constant="true"/>
        </listOfProducts>
        <kineticLaw>
          <math xmlns="http://www.w3.org/1998/Math/MathML">
            <ci> v_R1 </ci>
          </math>
        </kineticLaw>
      </reaction>
      <reaction id="R2" name="B1 &lt;-&gt; B2 (R2)" reversible="true" fast="false" fbc:lowerFluxBound="lb" fbc:upperFluxBound="ub">
        <listOfReactants>
          <speciesReference species="B1" stoichiometry="1" constant="true"/>
        </listOfReactants>
        <listOfProducts>
          <speciesReference species="B2" stoichiometry="1" constant="true"/>
        </listOfProducts>
        <kineticLaw>
          <math xmlns="http://www.w3.org/1998/Math/MathML">
            <ci> v_R2 </ci>
          </math>
        </kineticLaw>
      </reaction>
      <reaction id="R3" name="B2 export (R3)" reversible="true" fast="false" fbc:lowerFluxBound="lb" fbc:upperFluxBound="ub">
        <listOfReactants>
          <speciesReference species="B2" stoichiometry="1" constant="true"/>
        </listOfReactants>
        <listOfProducts>
          <speciesReference species="C" stoichiometry="1" constant="true"/>
        </listOfProducts>
        <kineticLaw>
          <math xmlns="http://www.w3.org/1998/Math/MathML">
            <ci> v_R3 </ci>
          </math>
        </kineticLaw>
      </reaction>
    </listOfReactions>
    <fbc:listOfObjectives fbc:activeObjective="R3_maximize">
      <fbc:objective fbc:id="R3_maximize" fbc:type="maximize">
        <fbc:listOfFluxObjectives>
          <fbc:fluxObjective fbc:reaction="R3" fbc:coefficient="1"/>
        </fbc:listOfFluxObjectives>
      </fbc:objective>
    </fbc:listOfObjectives>
  </model>
</sbml>
```

**Comment by 0u812** [comment]
Sorry for the regression, we did some refactoring and this option was dropped. It's fixed now. @matthiaskoenig can you build the binaries or do you want me to send them to you?

**Comment by 0u812** [comment]
Still need to fix other keys

**Comment by matthiaskoenig** [comment]
Build myself. Fixed in b37b691
<https://github.com/sys-bio/roadrunner/commit/b37b691262ddf52b06fd5de32c35a6163ef1e335>
.
Thanks so much.

On Wed, Oct 14, 2015 at 6:42 PM, Kyle Medley <notifications@github.com>
wrote:

> Closed #218 <https://github.com/sys-bio/roadrunner/issues/218> via b37b691
> <https://github.com/sys-bio/roadrunner/commit/b37b691262ddf52b06fd5de32c35a6163ef1e335>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sys-bio/roadrunner/issues/218#event-435429199>.
>



-- 
--------------------------------------------------------------
Matthias König
Computational Systems Biochemistry
Institute of Biochemistry
Charité - Universitätsmedizin Berlin
http://www.charite.de/sysbio/people/koenig/
Tel: + 49 30 450528449
Tel: + 49 176 81168480
--------------------------------------------------------------

**Comment by matthiaskoenig** [comment]
Still not possible to set the selections ! See attached example.

# create a selection array
sel = ['time'] \
        + ["".join(["[", item, "]"]) for item in
rr.model.getBoundarySpeciesIds()] \
        + ["".join(["[", item, "]"]) for item in
rr.model.getFloatingSpeciesIds()]

# set the selection !!! NOT WORKING ANY MORE. Why is it not possible ????
rr.selections = sel

This should give the following columns in results after simulations.
['time', '[A]', '[C]', '[B1]', '[B2]']
but only contains
time, [B1], [B2]

Please provide the old solution for setting selections.
How can I set the selections now ?

-----------------------------------
1.4.1; Compiler: gcc 4.8.4, C++ version: 199711; JIT Compiler: LLVM-3.4;
Date: Oct 14 2015, 19:47:29
    time, [B1], [B2]
 [[    0,    0,    0],
  [    2,    0,    0],
  [    4,    0,    0],
  [    6,    0,    0],
  [    8,    0,    0],
  [   10,    0,    0]]

['time', '[A]', '[C]', '[B1]', '[B2]']
    time, [B1], [B2]
 [[    0,    0,    0],
  [    2,    0,    0],
  [    4,    0,    0],
  [    6,    0,    0],
  [    8,    0,    0],
  [   10,    0,    0]]

    time, [B1], [B2]
 [[    0,    0,    0],
  [    2,    0,    0],
  [    4,    0,    0],
  [    6,    0,    0],
  [    8,    0,    0],
  [   10,    0,    0]]


On Wed, Oct 14, 2015 at 7:55 PM, Matthias König <konigmatt@googlemail.com>
wrote:

> Build myself. Fixed in b37b691
> <https://github.com/sys-bio/roadrunner/commit/b37b691262ddf52b06fd5de32c35a6163ef1e335>
> .
> Thanks so much.
>
> On Wed, Oct 14, 2015 at 6:42 PM, Kyle Medley <notifications@github.com>
> wrote:
>
>> Closed #218 <https://github.com/sys-bio/roadrunner/issues/218> via
>> b37b691
>> <https://github.com/sys-bio/roadrunner/commit/b37b691262ddf52b06fd5de32c35a6163ef1e335>
>> .
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/sys-bio/roadrunner/issues/218#event-435429199>.
>>
>
>
>
> --
> --------------------------------------------------------------
> Matthias König
> Computational Systems Biochemistry
> Institute of Biochemistry
> Charité - Universitätsmedizin Berlin
> http://www.charite.de/sysbio/people/koenig/
> Tel: + 49 30 450528449
> Tel: + 49 176 81168480
> --------------------------------------------------------------
>



-- 
--------------------------------------------------------------
Matthias König
Computational Systems Biochemistry
Institute of Biochemistry
Charité - Universitätsmedizin Berlin
http://www.charite.de/sysbio/people/koenig/
Tel: + 49 30 450528449
Tel: + 49 176 81168480
--------------------------------------------------------------

**Comment by 0u812** [comment]
rr.selections was renamed to rr.timeCourseSelections, see #128. We intentionally do this for clarity, as it's not intuitively clear whether selections refers to time course or steady state selections. I think @hsauro needs to make the call if we're going to support `rr.selections` for legacy code.

**Comment by 0u812** [comment]
I think we have approval from Herbert to support this, but this feature is deprecated, so please don't use it in new code.

**Comment by matthiaskoenig** [comment]
Does not have to be supported, but  a warning would be nice if someone
assigned something to rr.selections. Otherwise it will just fail silently.
Update the documentation for this: on the homepage it still provides the
rr.selections information.

On Wed, Oct 14, 2015 at 9:57 PM, Kyle Medley <notifications@github.com>
wrote:

> rr.selections was renamed to rr.timeCourseSelections, see #128
> <https://github.com/sys-bio/roadrunner/issues/128>. We intentionally do
> this for clarity, as it's not intuitively clear whether selections refers
> to time course or steady state selections. I think @hsauro
> <https://github.com/hsauro> needs to make the call if we're going to
> support rr.selections for legacy code.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sys-bio/roadrunner/issues/218#issuecomment-148178405>.
>



-- 
--------------------------------------------------------------
Matthias König
Computational Systems Biochemistry
Institute of Biochemistry
Charité - Universitätsmedizin Berlin
http://www.charite.de/sysbio/people/koenig/
Tel: + 49 30 450528449
Tel: + 49 176 81168480
--------------------------------------------------------------
